public class Main {
    public static void main(String[] args){
        int q = 100000;
        byte w =1 ;
        short e=1000;
        long r= 1000000000L;
        float t=1.3f;
        double y=1.3333333;
        byte a=67;
        short s=27897;
        short d=-159;
        short f=569;
        float g=2.786f;
        long h=987678965549L;
        float j=27.12f;
        byte lydmila=23;
        byte anna=27;
        byte ekaterina=30;
        byte all=80;
        short paper=480;
        System.out.println (" на каждого ученика расчитано "+ paper/all+ " листов бумаги");
        byte machine= 16;
        byte time=20;
        System.out.println ("за "+time+" минут машина произвела " +time*machine+ " штук бутылок");
        int Time= 720;
        System.out.println("за" +Time+" минут машина произвела "+Time*machine+" штук бутылок ");
        int TIme=2160;
        System.out.println("за" +TIme+" минут машина произвела "+TIme*machine+" штук бутылок ");
        int TIMe=21600;
        System.out.println("за" +TIMe+" минут машина произвела "+TIMe*machine+" штук бутылок ");
        byte white=2;
        byte brown=4;
        byte allPaints= 120;
        System.out.println(white+brown);
        byte oneClass=6;
        System.out.println(allPaints/oneClass);
        byte classs=20;
        System.out.println("в школе где "+classs+" классов нужно "+classs*white+" банок белой краски и "+classs*brown+" банок коричневой краски ");
        byte banana=5;
        byte bananaWeight=80;
        short milk=200;
        milk =2;
        short milkWeight=105;
        byte iceCream=2;
        byte iceCreamWeight=100;
        byte egg=4;
        byte eggWeight=70;
        System.out.println(milkWeight*milk + banana*bananaWeight + iceCream*iceCreamWeight + egg*eggWeight);
        short allWeight=1090;
        System.out.println(allWeight/(float)1000);
        float allWeightKg=1.09f;
        short needToLoseGr= 7000;
        short oneDayLoseGr=250;
        System.out.println(needToLoseGr/oneDayLoseGr);
        short oneDayLoseKg=500;
        System.out.println(needToLoseGr/oneDayLoseKg);
        byte oneDayLose250Gr=28;
        byte oneDayLose500Gr=14;
        System.out.println(oneDayLose500Gr+oneDayLose250Gr);
        byte allDays=42;
        System.out.println(allDays/2);
        byte daysAverage=21;
        int macha=67760;
        int denis=83690;
        int kristina=76230;
        System.out.println(macha*12);
        System.out.println(denis*12);
        System.out.println(kristina*12);
        int annualIncomeMacha=813120;
        int annualIncomeDenis=1004280;
        int annualIncomeKristina=914760;
        System.out.println(macha/(float)100*10);
        System.out.println(denis/(float)100*10);
        System.out.println(kristina/(float)100*10);
        short machaDifference=6776;
        short denisDifference=8369;
        short kristinaDifference=7623;
        System.out.println(macha+machaDifference);
        System.out.println(macha+denisDifference);
        System.out.println(kristina+kristinaDifference);
        int newMacha=74536;
        int newDenis=92059;
        int newKristina=83853;
        System.out.println(newMacha*12);
        System.out.println(newDenis*12);
        System.out.println(newKristina*12);
        int newAnnualIncomeMacha=894432;
        int newAnnualIncomeDenis=1104708;
        int newAnnualIncomeKristina=1006236;
        System.out.println(newAnnualIncomeMacha-annualIncomeMacha);
        System.out.println(newAnnualIncomeDenis-annualIncomeDenis);
        System.out.println(newAnnualIncomeKristina-annualIncomeKristina);
        int differenceMacha=81312;
        int differenceDenis=100428;
        int differenceKristina=91476;
        System.out.println(" Маша теперь получет "+newAnnualIncomeMacha+" рублей. Годовой доход вырос на "+differenceMacha+" рублей" );
        System.out.println(" Денис теперь получет "+newAnnualIncomeDenis+" рублей. Годовой доход вырос на "+differenceDenis+" рублей" );
        System.out.println(" Кристина теперь получет "+newAnnualIncomeKristina+" рублей. Годовой доход вырос на "+differenceKristina+" рублей" );
    }
}